<h2>A Propos</h2>
<p>Pour la réalisation de cet exercice, les seules librairies externes sont : </p>
<ul>
    <li>Twitter Bootstrap</li>
    <li>
        <ul>
            <li>Theme FLAT UI</li>
        </ul>
    </li>
    <li>jQuery</li>
    <li>
        <ul>
            <li>Les composants JQXWidgets</li>
            <li>Pour la gestion de l'arbre des catégories</li>
        </ul>
    </li>
</ul>

<p>Le framework MVC a été entièrement recodé "from scratch". Je me suis inspiré du fonctionnement de cakePHP pour certaines parties</p>
<p><small>Il n'y a donc aucune relation avec les différents framework "MiniMVC" qui sont sur github</small></p>